### PR TITLE
Added a Custom debugger path and a function to execute code instead of getting a shell directly

### PR DESCRIPTION
**Pull request by zAbuQasem**
image

### CODE REVIEW

**Comment by Ruulian** [comment]
Hi! Thanks for you PR, I like your idea and I want to add it on the repository. However, I didn't get why you've created a `runner` method and a `spawn_shell` attribute since we can directly call `extractor.debugger()` and `extractor.shell()`.

**Comment by zAbuQasem** [comment]
Hello @Ruulian , You are right, there are no need for that extra code so i removed it

Thanks!

**Comment by Ruulian** [comment]
Thanks for the update! I'll test it today or tomorrow 🙂

**Comment by zAbuQasem** [comment]
I have to mention that i didn't edit the output html parser for the `debugger()`

**Comment by Ruulian** [comment]
Yes I just checked, however, the output is not the same depending on if it was the result of a shell command (using stdout I guess) or a python command.

When you execute a python command, it creates a `<div>` tag for each python command and the output is appended to the command string:
image

When you execute a shell command, it creates a `<div>` tag as well, but it creates a `<span>` to store the output:
image

In `exec_cmd` I parse the HTML using the `<span>` tag, so when you execute a simple python command it doesn't work:
image

Therefore, `exec_dbg` must handle 2 cases:
- A simple python command : parse the `<div>` without using the `<span>`
- A python command that generates output on stdout: parse as `exec_dbg` is doing

I think that the best solution is to create a function `parse_result` that parse the html result depending on if there is a span inside.

PS: For the errors the output is the same for both cases, so your code works successfully:
image

**Comment by zAbuQasem** [comment]
Done!

**Comment by Ruulian** [comment]
Hi, I was wrong about the parsing of HTML, the process is a bit more complicated. It creates some span in order to get a pretty print (not about stdout or whatever).
Therefore, I fixed the `parse_html` to avoid you re-doing something you've already done with my wrong indications..
I also changed the rich output, it was a bit too much. Instead, I used the print function of the rich library to display the output of the debugger, your idea was great :+1: .

Can you confirm that the changes are okey for you so I can merge the PR?

**Comment by zAbuQasem** [comment]
Thanks for the updates, all look good but a small issue with the output of shell commands:
image

I tried to use the same `WConsoleExtractor.sanitize_command_output(output)` function to sanitize the output, but the `print(1)` won't show any output

**Comment by Ruulian** [comment]
It is not an issue.
In the debugger, we send python code so we receive python types. The return type of `check_output` is of type bytes, so it displays bytes.
In case of the shell, we send bash commands so we receive bash output, that's why we remove the quotes in `shell` command.

**Comment by zAbuQasem** [comment]
Got it!
Thanks @Ruulian , i think we are ready to merge now

**Comment by zAbuQasem** [comment]
Added switch commands to switch between debugger and shell

image

**Comment by zAbuQasem** [comment]
It would be awesome if the prompt , error and info are printing with colors, what do you think @Ruulian

**Comment by Ruulian** [comment]
Which colors do you think? (I'm in vacation rn, don't have my laptop)

**Comment by zAbuQasem** [comment]
Hello @Ruulian , I hope you had a nice and relaxing vacation!

are there any pending changes you want me to add in order to merge this PR

Thanks in advance

**Comment by Ruulian** [comment]
Hello, maybe you can fix the conflict related to PR #2 (the PR was fixing something I needed), in order to merge easily.

**Comment by zAbuQasem** [comment]
all should be good now
@Ruulian

**Comment by Ruulian** [comment]
I did a commit to solve some small issues, if everything is okey for you, I can merge.

**Comment by zAbuQasem** [comment]
All good @Ruulian

**Pull request merged**
